version: 2

jobs:
  # Build job
  build:
    working_directory: ~/tanb/xn--sn8h24a
    docker:
      - image: circleci/node:9.11-browsers
    steps:
      - checkout
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Cleaning
          command: make clean-node-modules clean-dist
      - run:
          name: Install node-modules
          command: make node-modules
      - run:
          name: Building
          command: make release-build
      - persist_to_workspace:
          root: ./
          paths:
            - dist
  # Deploy job
  deploy:
    working_directory: ~/tanb/xn--sn8h24a
    docker:
      - image: circleci/node:9.11-browsers
    steps:
      - checkout
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - attach_workspace:
          at: ./
      - run:
          name: Install awscli
          command: sudo apt-get -y -qq install awscli
      - run:
          name: Setting aws region
          command: aws configure set region ap-northeast-1
      - run:
          name: Setting Signature Version 4 for S3 Request Authentication
          command: aws configure set default.s3.signature_version s3v4
      - run:
          name: Deploy to S3
          command: aws s3 sync dist/tanb-express s3://app.tanb/ --delete --cache-control "no-cache"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      # The deploy job will only run on the filtered branches and
      # require the build job to be successful before it starts
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - release
