backend:
  name: git-gateway
  branch: release

media_folder: 'src/assets/img/uploads' # Folder where user uploaded files should go
public_folder: 'assets/img/uploads'
publish_mode: editorial_workflow

collections: # A list of collections the CMS should be able to edit
  - name: 'blog' # Used in routes, ie.: /admin/collections/:slug/edit
    label: 'Blog' # Used in the UI, ie.: "New Post"
    folder: 'blog' # (src/assets/blog) The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: 'Layout', name: 'layout', widget: 'hidden', default: 'blog'}
      - {label: 'Featured Image', name: 'featured_image', widget: 'image', required: false}
      - {label: 'Title', name: 'title', widget: 'string', required: true}
      - {label: 'Description', name: 'description', widget: 'string', required: false}
      - {label: 'Publish', name: 'publish', widget: 'boolean', required: false}
      - {label: 'Publish Date', name: 'publish_date', widget: 'datetime', required: false}
      - {label: 'Body', name: 'body', widget: 'markdown', required: true}
